### PR TITLE
angular set up

### PR DESCRIPTION
**Pull request by HenryWedge**

### CODE REVIEW

**Review by NoahPeeters — APPROVED** [review]

**Review by TilBlechschmidt — CHANGES_REQUESTED** [review]
The following files should not be present and have probably been created due to misuse of `yarn` in the root directory and/or use of `npm` in the `/frontend` subdirectory.
- [ ] `/yarn.lock`
- [ ] `/api/package-lock.json`
- [ ] `/frontend/survey-app/package-lock.json`
- [ ] `/frontend/package-lock.json` it is unclear why this and the above one both exist. This is probably not intentional and signals some other issue at hand
- [ ] `/frontend/.gitkeep` is now redundant

**Review by NoahPeeters — CHANGES_REQUESTED** [review]
Please remove `yarn.lock`, `/api/package-lock.json`, /frontend/package-lock.json` and `/frontend/.gitkeep`.

**Comment by TilBlechschmidt** [comment]
To elaborate on the creation of the `yarn.lock` and `package-lock.json` in the project root and frontend subdirectory respectively: When executing `npm` or `yarn` in a folder that does not contain a `package.json` the command exits with an error code but does create a lock file. This seems to have caused the creation of the former. The latter looks like it has been accidentally copied from the subdirectory.

Additional question: Is there any reason why the Angular App has to reside in `frontend/survey-app/` instead of just `frontend/`?

**Comment by NoahPeeters** [comment]
LGTM now.

We should consider to add some instructions to `/README.md` for the initial project configuration during development. Something like this:

```sh
# Setup API
cd api
yarn install
yarn generate

# Setup and start frontend
cd frontend
yarn install
ng serve
```

Later we can extend that with the setup instructions for the backend.

**Review by TilBlechschmidt — APPROVED** [review]

**Review by TilBlechschmidt — APPROVED** [review]

**Review by NoahPeeters — APPROVED** [review]

**Pull request merged**
