### PR TITLE
🐳 Add Dockerfile and docker-compose support

### PR DESCRIPTION
**Pull request by TilBlechschmidt**
This PR adds `Dockerfiles` for both the frontend and the backend which are individually fully functional. Additionally, a `docker-compose.yml` has been added which isolates the individual services in their own network and provides a reverse proxy to make everything available on a single endpoint.

### CODE REVIEW

**Comment by hpr1999** [comment]
Alright, this "works on my machine", so big thumbs up. It definitely takes more than 5 minutes to install initially, but that's really not surprising. It looks good, but  I'm really not in the position to review docker files, I just don't know enough.
Maybe @HenryWedge or @NoahPeeters can have a look? 
Small comment: The backend can't be accessed directly, I guess that's intentional?

**Comment by TilBlechschmidt** [comment]
Regarding the backend, it is isolated in its own network and can thus may not be accessed directly. However, it be accessed by visiting `localhost:2020/api`. This has been implemented using a reverse proxy so that both the frontend and backend are available on the same port. In the future, it should remedy any configuration issues with the frontend as it would be way harder to configure the frontend to properly access the backend if they are on different hosts/ports (things like CORS, Config Files etc.). With this solution the frontend may have a line that checks for production mode and accesses `/api` instead of using a FQDN.

The major problem with the installation is that it contains the download of all prerequisites (JDK, NodeJS, Gradle) and dependencies. Even the GitHub Actions pipeline takes roughly 3.5 minutes in total for the whole build process and one should keep in mind that most prerequisites are already installed and it has a heavily cached Gigabit uplink. I honestly doubt that anything can be done to make the build process any faster on initial build (subsequent builds are significantly faster since all prerequisites and dependencies are being cached, I've taking special consideration to allow this).

Then again, it is basically setting the project up from scratch. It basically leaves us with the choice of providing him with manual installation instructions and hoping that he has the necessary tools already installed — albeit at the cost of potential user error or some version mismatches (e.g. he might not have JDK15 installed but JDK13 and try it with that by mistake) — or to just trade the automated, deterministic process for a few more minutes.

In my eyes it makes more sense to use the automatic process since I'd presume the 5min limitation is for him to not get frustrated during setup. If he can just fire and forget and grab a coffee it is presumably fine as well* ☕

*We might want to ask him on that though

**Comment by hpr1999** [comment]
> Regarding the backend, it is isolated in its own network and thus may not be accessed directly. However, it can be accessed by visiting localhost:2020/api. 

Yeah I just found that out moments after that comment - my mistake.

> In my eyes it makes more sense to use the automatic process since I'd presume the 5min limitation is for him to not get frustrated during setup. If he can just fire and forget and grab a coffee it is presumably fine as well* coffee

> *We might want to ask him on that though 

I totally agree, on both points.

**Comment by TilBlechschmidt** [comment]
By the way, note that the Spring Boot Context Path [has been set to accommodate the new URL prefix](https://github.com/TilBlechschmidt/NAK-IAA/pull/10/files?file-filters%5B%5D=.md&file-filters%5B%5D=.yml&file-filters%5B%5D=No+extension#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R28) (basically all redirects/references of the backend will be aware of the reverse proxy).

**Review by NoahPeeters — DISMISSED** [review]

**Review by HenryWedge — APPROVED** [review]
Now working for me after some issues with windows line endings and docker version. A small note to use the latest docker version and use unix line endings in the READ.ME or documentation might be useful

**Review by hpr1999 — APPROVED** [review]

**Pull request merged**
