### PR TITLE
feat: :tada: Set up SpringBoot backend

### PR DESCRIPTION
**Pull request by hpr1999**

### CODE REVIEW

**Comment by TilBlechschmidt** [comment]
I'm by no means an expert in this area but shouldn't the repository contain a template for the `application.properties` and upon deployment or local development it gets generated based on the template and environment variables present at build time? (Again, just a faint memory of working w/ Spring in a larger context wouldn't call it a guaranteed thing)

**Review by NoahPeeters — APPROVED** [review]

**Comment by NoahPeeters** [comment]
@TilBlechschmidt we had another look at this and everything we found online said that this file should be added to git. One can have other profiles and those might not be added to git. But the base configuration should be added to git.

**Comment by hpr1999** [comment]
Seconded @NoahPeeters.

@TilBlechschmidt We would prefer it if this check would be disabled, if possible, instead of simply merging it against the policy.
Opinions?

**Comment by TilBlechschmidt** [comment]
image
Done.

**Pull request merged**
